version: '3.8'

services:
  mosquitto:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2.0.16
    ports:
      - 1883:2883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mosquitto
  
  sensor-simulator:
    container_name: sensor-simulator
    restart: unless-stopped
    build: ./sensor-simulator/.
    depends_on:
      - mosquitto
    environment:
      SENSOR_ID: sensor-simulator
      MQQT_HOSTNAME: mosquitto
      MQQT_PORT: 2883
      MQQT_TOPIC_TEMPRATURE: 'sensor/temprature'
      MQQT_TOPIC_HUMIDITY: 'sensor/humidity'
      SQL_DB_NAME: 'sensor_simulator'
      SQL_DB_TABLE_NAME: 'unpublished_data'
    volumes:
      - ./sensor-simulator:/myapp
    networks:
      - mosquitto
  
  mongodb:
    container_name: mongodb
    restart : unless-stopped
    image: mongo:7.0.1-rc0-jammy
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - mongodb
  
  data-collector:
    container_name: data-collector
    restart: unless-stopped
    build: ./data-collector/.
    depends_on:
      - mosquitto
      - mongodb
    environment:
      MQQT_HOSTNAME: mosquitto
      MQQT_PORT: 2883
      MQQT_TOPIC: 'sensor/#'
      MONGO_DB_USERNAME: mongo_admin
      MONGO_DB_PASSWORD: mongo_admin
      MONGO_DB_HOSTNAME: mongodb
      MONGO_DB_NAME: sensordata
    volumes:
      - ./data-collector:/myapp
    networks:
      - mosquitto
      - mongodb

volumes:
  mosquitto:
  sensor-simulator:
  data-collector:

networks:
  mosquitto:
    driver: bridge
  mongodb:
    driver: bridge