version: '3.8'

services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.16
    ports:
      - 1883:2883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mosquitto
  
  sensor-simulator-1:
    container_name: sensor-simulator-1
    build: ./sensor-simulator/.
    depends_on:
      - mosquitto
    environment:
      SENSOR-ID: sensor-simulator-1
      MQQT-HOSTNAME: mosquitto
      MQQT-PORT: 2883
      MQQT-TOPIC-TEMPRATURE: 'sensor/temprature'
    volumes:
      - ./sensor-simulator:/myapp
    networks:
      - mosquitto

volumes:
  mosquitto:
  sensor-simulator:

networks:
  mosquitto:
    driver: bridge