version: '3.8'

services:
  mosquitto:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2.0.16
    ports:
      - 1883:2883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mosquitto
  
  sensor-simulator:
    container_name: sensor-simulator
    restart: unless-stopped
    build: ./sensor-simulator/.
    depends_on:
      - mosquitto
    environment:
      SENSOR_ID: sensor-simulator
      SQL_DB_NAME: 'sensor_simulator'
      SQL_DB_TABLE_NAME: 'unpublished_data'
    env_file:
      - .env
    volumes:
      - ./sensor-simulator:/myapp
    networks:
      - mosquitto
  
  mongodb:
    container_name: mongodb
    restart : unless-stopped
    image: mongo:7.0.1-rc0-jammy
    command: mongod --quiet --logpath /dev/null 
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - mongodb

  redisdb:
    container_name: redisdb
    restart : unless-stopped
    image: redis:7.2.0-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - ./redisdb/data:/data
    networks:
      - redisdb
  
  data-collector:
    container_name: data-collector
    restart: unless-stopped
    build: ./data-collector/.
    depends_on:
      - mosquitto
      - mongodb
      - redisdb
    environment:
      MQQT_TOPIC: 'sensor/#'
    env_file:
      - .env
    volumes:
      - ./data-collector:/myapp
    networks:
      - mosquitto
      - mongodb
      - redisdb
  
  web-api:
    container_name: web-api
    restart: unless-stopped
    build: ./web-api/.
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - redisdb
    env_file:
      - .env
    volumes:
      - ./web-api:/myapp
    networks:
      - mongodb
      - redisdb

volumes:
  mosquitto:
  sensor-simulator:
  data-collector:
  redisdb:

networks:
  mosquitto:
    driver: bridge
  mongodb:
    driver: bridge
  redisdb:
    driver: bridge